TIME: 1000
PATH_TO_SAVE_MODEL: 'exp1_MNIST_T1000_epochs10_lr0001.pth'
EPOCHS: 100
device: 'cuda'
batch_size: 32
in_channels: 1
out_channels: 1
dataset: 'MNIST'
num_classes: 10
recommended_steps: [1,2,2,2]
recommended_attn_step_indexes: [1,2,3,4]
p_cond: 0.2
lr: 0.0001
lr_warmup: 0.0001
alpha_max: 0.0003
alpha_min: 0.0000003
T_w: 1000
T_c: 15000 
beta1: 0.9
beta2: 0.999
eps: 0.00001
weight_decay: 0.001
device: "cuda"
dtype: "float32"
log_interval: 100
prefix_name_experiment: 'exp1_lr001_eps15_nlayers4_nheads16_bSize16_wd001'